<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Kebur Fantahun, Ricco Ferraro" />

<meta name="date" content="2021-03-07" />

<title>Beers and Breweries Analysis</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="site_libs/datatables-binding-0.17/datatables.js"></script>
<link href="site_libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="bio.html">About Me</a>
</li>
<li>
  <a href="BeersAndBrews.html">Beers Analysis</a>
</li>
<li>
  <a href="BeerInteract.html">Interact with Beer Data</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Beers and Breweries Analysis</h1>
<h4 class="author">Kebur Fantahun, Ricco Ferraro</h4>
<h4 class="date">03/07/2021</h4>

</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>With the pandemic in full swing, craft breweries across the nation are closing their doors. Social distancing and other precautionary stay at home orders have forever changed the market for craft beer. This presents a unique opportunity to Anheuser-Busch InBev. In many ways, the market is wide open. Craft beer, especially IPA's and ales in the US can be shown to follow certain trends with regards to bitterness and ABV. Adhering to these trends may help ensure, when choosing which breweries to procure for example, that an investment is successful.</p>
<p>With the craft beer data provided by Anheuser-Busch InBev, this report will depict the apparent relationship between alcohol by volume(ABV) and international bitterness units(IBU) for myriad beers across the United States. The report also provides summary statistics such as minimums, medians and maximums with respect to ABV and IBU, as well as a deeper look in to the difference between IPA's and &quot;Other Ale's&quot;(any beer with Ale in the name) with respect to ABV and IBU. Our analysis reveals information that could be useful to Anheuser-Busch InBev concerning beer volumes in ounces as they relate to each state of the US.</p>
<div id="dataset" class="section level3">
<h3>Dataset</h3>
<p>The beers and breweries dataset provided by Anheuser-Busch InBev contain information about 2410 US craft beers and 558 US breweries. The datasets are as follows:</p>
<p><strong>Beers.csv:</strong><br />
* Name: Name of the beer.<br />
* Beer_ID: Unique identifier of the beer.<br />
* ABV: Alcohol by volume of the beer.<br />
* IBU: International Bitterness Units of the beer.<br />
* Brewery_ID: Brewery id associated with the beer.<br />
* Style: Style of the beer.<br />
* Ounces: Ounces of beer.</p>
<p><strong>Breweries.csv:</strong><br />
* Brew_ID: Unique identifier of the brewery.<br />
* Name: Name of the brewery.<br />
* City: City where the brewery is located.<br />
* State: U.S. State where the brewery is located.</p>
</div>
<div id="problem-statment" class="section level3">
<h3>Problem statment</h3>
<p>This report is tasked with:<br />
* analyzing the number of breweries in each state in the US<br />
* correcting missing IBU Data<br />
* analyzing minimum, median, and maximum ABV and IBU for each state<br />
* providing general summary statistics for ABV<br />
* determining if a relationship between IBU and ABV exists<br />
* analyzing the IBU and ABV relationship for IPA's vs other Ales<br />
* providing other meaningful insight</p>
</div>
</div>
<div id="libraries" class="section level1">
<h1>Libraries</h1>
<div id="import-data" class="section level3">
<h3>Import Data</h3>
<p><em>Note: we use the merge data in Question 1 and therefore we need to perform step 2 first.</em></p>
</div>
</div>
<div id="merge-beer-data-first-with-the-breweries-data-print-first-6-and-last-6-oservations-in-merged-file." class="section level1">
<h1>2. Merge beer data first with the breweries data &amp; Print first 6 and last 6 oservations in merged file.</h1>
<table>
<colgroup>
<col width="9%" />
<col width="11%" />
<col width="6%" />
<col width="5%" />
<col width="3%" />
<col width="28%" />
<col width="6%" />
<col width="14%" />
<col width="9%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Brewery_id</th>
<th align="left">Drink_name</th>
<th align="right">Beer_ID</th>
<th align="right">ABV</th>
<th align="right">IBU</th>
<th align="left">Style</th>
<th align="right">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">Get Together</td>
<td align="right">2692</td>
<td align="right">0.045</td>
<td align="right">50</td>
<td align="left">American IPA</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">Maggie's Leap</td>
<td align="right">2691</td>
<td align="right">0.049</td>
<td align="right">26</td>
<td align="left">Milk / Sweet Stout</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">Wall's End</td>
<td align="right">2690</td>
<td align="right">0.048</td>
<td align="right">19</td>
<td align="left">English Brown Ale</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">Pumpion</td>
<td align="right">2689</td>
<td align="right">0.060</td>
<td align="right">38</td>
<td align="left">Pumpkin Ale</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">Stronghold</td>
<td align="right">2688</td>
<td align="right">0.060</td>
<td align="right">25</td>
<td align="left">American Porter</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">Parapet ESB</td>
<td align="right">2687</td>
<td align="right">0.056</td>
<td align="right">47</td>
<td align="left">Extra Special / Strong Bitter (ESB)</td>
<td align="right">16</td>
<td align="left">NorthGate Brewing</td>
<td align="left">Minneapolis</td>
<td align="left">MN</td>
</tr>
</tbody>
</table>
<table style="width:100%;">
<colgroup>
<col width="3%" />
<col width="7%" />
<col width="17%" />
<col width="5%" />
<col width="4%" />
<col width="3%" />
<col width="16%" />
<col width="5%" />
<col width="20%" />
<col width="9%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Brewery_id</th>
<th align="left">Drink_name</th>
<th align="right">Beer_ID</th>
<th align="right">ABV</th>
<th align="right">IBU</th>
<th align="left">Style</th>
<th align="right">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2405</td>
<td align="right">556</td>
<td align="left">Pilsner Ukiah</td>
<td align="right">98</td>
<td align="right">0.055</td>
<td align="right">NA</td>
<td align="left">German Pilsener</td>
<td align="right">12</td>
<td align="left">Ukiah Brewing Company</td>
<td align="left">Ukiah</td>
<td align="left">CA</td>
</tr>
<tr class="even">
<td align="left">2406</td>
<td align="right">557</td>
<td align="left">Heinnieweisse Weissebier</td>
<td align="right">52</td>
<td align="right">0.049</td>
<td align="right">NA</td>
<td align="left">Hefeweizen</td>
<td align="right">12</td>
<td align="left">Butternuts Beer and Ale</td>
<td align="left">Garrattsville</td>
<td align="left">NY</td>
</tr>
<tr class="odd">
<td align="left">2407</td>
<td align="right">557</td>
<td align="left">Snapperhead IPA</td>
<td align="right">51</td>
<td align="right">0.068</td>
<td align="right">NA</td>
<td align="left">American IPA</td>
<td align="right">12</td>
<td align="left">Butternuts Beer and Ale</td>
<td align="left">Garrattsville</td>
<td align="left">NY</td>
</tr>
<tr class="even">
<td align="left">2408</td>
<td align="right">557</td>
<td align="left">Moo Thunder Stout</td>
<td align="right">50</td>
<td align="right">0.049</td>
<td align="right">NA</td>
<td align="left">Milk / Sweet Stout</td>
<td align="right">12</td>
<td align="left">Butternuts Beer and Ale</td>
<td align="left">Garrattsville</td>
<td align="left">NY</td>
</tr>
<tr class="odd">
<td align="left">2409</td>
<td align="right">557</td>
<td align="left">Porkslap Pale Ale</td>
<td align="right">49</td>
<td align="right">0.043</td>
<td align="right">NA</td>
<td align="left">American Pale Ale (APA)</td>
<td align="right">12</td>
<td align="left">Butternuts Beer and Ale</td>
<td align="left">Garrattsville</td>
<td align="left">NY</td>
</tr>
<tr class="even">
<td align="left">2410</td>
<td align="right">558</td>
<td align="left">Urban Wilderness Pale Ale</td>
<td align="right">30</td>
<td align="right">0.049</td>
<td align="right">NA</td>
<td align="left">English Pale Ale</td>
<td align="right">12</td>
<td align="left">Sleeping Lady Brewing Company</td>
<td align="left">Anchorage</td>
<td align="left">AK</td>
</tr>
</tbody>
</table>
</div>
<div id="how-many-breweries-are-in-each-state" class="section level1">
<h1>1. How many breweries are in each state?</h1>
<p>There are a range of breweries for state and they are visible in the state. This could be due to a variety of reasons such as taxation, availability and cost of materials, releastate, demographics or that state etc. In our dataset, Colorado for example has 47 craft breweries and California has 39 craft breweries and Arizona has 11. This dataset obviously does not represent all craft breweries in the state, so it is important to note that it is the relative proportion of craft breweries we are interested in here. In many cases, the craft brewery number is most likely tied to state population. See the Pie chart for the breakdown. See Table:</p>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div id="htmlwidget-fb17bf0fdb2630dfae51" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-fb17bf0fdb2630dfae51">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51"],["AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VA","VT","WA","WI","WV","WY"],[7,3,2,11,39,47,8,1,2,15,7,4,5,5,18,22,3,4,5,23,7,9,32,12,9,2,9,19,1,5,3,3,4,2,16,15,6,29,25,5,4,1,3,28,4,16,10,23,20,1,4]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>State<\/th>\n      <th>unique_breweries<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":2},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<pre><code>## [1] &quot;Total Unique Breweries: &quot;</code></pre>
<pre><code>## [1] 558</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
</div>
<div id="assess-missing-data" class="section level1">
<h1>3. Assess missing data</h1>
<div id="plot-missing-data-for-reference" class="section level2">
<h2>Plot missing data for reference</h2>
<pre><code>## Warning in plot.aggr(res, ...): not enough horizontal space to display frequencies</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre><code>## 
##  Variables sorted by number of missings: 
##    Variable       Count
##         IBU 0.417012448
##         ABV 0.025726141
##       Style 0.002074689
##  Brewery_id 0.000000000
##  Drink_name 0.000000000
##     Beer_ID 0.000000000
##      Ounces 0.000000000
##     Brewery 0.000000000
##        City 0.000000000
##       State 0.000000000</code></pre>
<pre><code>##    Brewery_id     Drink_name           Beer_ID            ABV               IBU            Style               Ounces        Brewery         
##  Min.   :  1.0   Length:2410        Min.   :   1.0   Min.   :0.00100   Min.   :  4.00   Length:2410        Min.   : 8.40   Length:2410       
##  1st Qu.: 94.0   Class :character   1st Qu.: 808.2   1st Qu.:0.05000   1st Qu.: 21.00   Class :character   1st Qu.:12.00   Class :character  
##  Median :206.0   Mode  :character   Median :1453.5   Median :0.05600   Median : 35.00   Mode  :character   Median :12.00   Mode  :character  
##  Mean   :232.7                      Mean   :1431.1   Mean   :0.05977   Mean   : 42.71                      Mean   :13.59                     
##  3rd Qu.:367.0                      3rd Qu.:2075.8   3rd Qu.:0.06700   3rd Qu.: 64.00                      3rd Qu.:16.00                     
##  Max.   :558.0                      Max.   :2692.0   Max.   :0.12800   Max.   :138.00                      Max.   :32.00                     
##                                                      NA&#39;s   :62        NA&#39;s   :1005                                                          
##      City               State     
##  Length:2410        CO     : 265  
##  Class :character   CA     : 183  
##  Mode  :character   MI     : 162  
##                     IN     : 139  
##                     TX     : 130  
##                     OR     : 125  
##                     (Other):1406</code></pre>
<div id="remove-data-for-entries-missing-both-ibu-and-abv-when-there-is-no-data-online" class="section level3">
<h3>Remove Data for entries missing both IBU and ABV when there is no data online</h3>
<ol style="list-style-type: decimal">
<li>Special Release, The Crowler^tm, Can'd aid foundation are missing ABV/IBU/Style</li>
<li>Cedar creek - Special Release is ambiguous, missing ABV/IBU/Style and will be dropped as it does not solve the QOI.</li>
<li>Oskar Blues Brewery - The Crowler is not an actual beer but a type of can</li>
<li>Oskar Blues Brewery - Can'd aid foundation is a relief effort that sends water so it does not fit in the dataset.</li>
<li>Beer ID 2364, Royal Lager of Weston Brewing has no ABV/IBU</li>
<li>Same for BID - 2322 Fort Pitt Brewing Company Fort Pitt Ale</li>
<li>Oskar Blues Brewery Birth IPA, 1750</li>
<li>710, no data</li>
<li>MillKing It Productions AXL Pale Ale, 273 - out of business no info</li>
<li>1095 no data</li>
<li>963 no data</li>
</ol>
</div>
<div id="hand-enter-all-data-missing-ibu-and-abv.-note-this-data-was-all-available-publicly" class="section level3">
<h3>Hand enter all data missing <code>IBU</code> AND <code>ABV</code>. Note: this data was all available publicly</h3>
<ul>
<li>Add style data for 2527 and 1635 by looking it up by hand.<br />
</li>
<li>Add IBU and ABV Data for many missing rows by looking up by hand (online via <code>BeerAdvocate.com</code> or <code>Untappd.com</code>)</li>
</ul>
<pre><code>## Matching, by = &quot;Beer_ID&quot;</code></pre>
</div>
<div id="impute-ibu-based-on-median-ibu-by-style-for-entries-that-only-lack-ibu-data" class="section level3">
<h3>Impute IBU based on Median IBU by style for entries that ONLY lack IBU data</h3>
<table>
<colgroup>
<col width="2%" />
<col width="9%" />
<col width="11%" />
<col width="10%" />
<col width="11%" />
<col width="11%" />
<col width="9%" />
<col width="11%" />
<col width="11%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Brewery_id</th>
<th align="left">ABV</th>
<th align="left">IBU</th>
<th align="left">Drink_name</th>
<th align="left">Style</th>
<th align="left">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Min. : 1.0</td>
<td align="left">Min. :0.00100</td>
<td align="left">Min. : 3.57</td>
<td align="left">Length:2400</td>
<td align="left">Length:2400</td>
<td align="left">Min. : 8.40</td>
<td align="left">Length:2400</td>
<td align="left">Length:2400</td>
<td align="left">CO : 261</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">1st Qu.: 94.0</td>
<td align="left">1st Qu.:0.05000</td>
<td align="left">1st Qu.: 21.00</td>
<td align="left">Class :character</td>
<td align="left">Class :character</td>
<td align="left">1st Qu.:12.00</td>
<td align="left">Class :character</td>
<td align="left">Class :character</td>
<td align="left">CA : 183</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Median :206.5</td>
<td align="left">Median :0.05600</td>
<td align="left">Median : 35.00</td>
<td align="left">Mode :character</td>
<td align="left">Mode :character</td>
<td align="left">Median :12.00</td>
<td align="left">Mode :character</td>
<td align="left">Mode :character</td>
<td align="left">MI : 161</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Mean :232.6</td>
<td align="left">Mean :0.05969</td>
<td align="left">Mean : 42.59</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">Mean :13.58</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">IN : 139</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">3rd Qu.:367.0</td>
<td align="left">3rd Qu.:0.06700</td>
<td align="left">3rd Qu.: 64.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">3rd Qu.:16.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">TX : 129</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Max. :558.0</td>
<td align="left">Max. :0.12800</td>
<td align="left">Max. :138.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">Max. :32.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">OR : 125</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA's :976</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">(Other):1402</td>
</tr>
</tbody>
</table>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>##  [1] Style               Brewery_id          ABV                 Drink_name          Ounces              Brewery             City               
##  [8] State               median_IBU_by_style IBU.clean          
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="2%" />
<col width="10%" />
<col width="8%" />
<col width="9%" />
<col width="10%" />
<col width="8%" />
<col width="10%" />
<col width="10%" />
<col width="8%" />
<col width="12%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Style</th>
<th align="left">Brewery_id</th>
<th align="left">ABV</th>
<th align="left">Drink_name</th>
<th align="left">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
<th align="left">median_IBU_by_style</th>
<th align="left">IBU.clean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Length:2348</td>
<td align="left">Min. : 1</td>
<td align="left">Min. :0.02700</td>
<td align="left">Length:2348</td>
<td align="left">Min. : 8.40</td>
<td align="left">Length:2348</td>
<td align="left">Length:2348</td>
<td align="left">CO : 258</td>
<td align="left">Min. : 8.00</td>
<td align="left">Min. : 3.57</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Class :character</td>
<td align="left">1st Qu.: 92</td>
<td align="left">1st Qu.:0.05000</td>
<td align="left">Class :character</td>
<td align="left">1st Qu.:12.00</td>
<td align="left">Class :character</td>
<td align="left">Class :character</td>
<td align="left">CA : 181</td>
<td align="left">1st Qu.:21.00</td>
<td align="left">1st Qu.: 21.00</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Mode :character</td>
<td align="left">Median :204</td>
<td align="left">Median :0.05600</td>
<td align="left">Mode :character</td>
<td align="left">Median :12.00</td>
<td align="left">Mode :character</td>
<td align="left">Mode :character</td>
<td align="left">MI : 146</td>
<td align="left">Median :30.00</td>
<td align="left">Median : 32.00</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">Mean :231</td>
<td align="left">Mean :0.05967</td>
<td align="left">NA</td>
<td align="left">Mean :13.56</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">IN : 139</td>
<td align="left">Mean :40.03</td>
<td align="left">Mean : 40.46</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">3rd Qu.:366</td>
<td align="left">3rd Qu.:0.06700</td>
<td align="left">NA</td>
<td align="left">3rd Qu.:16.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">TX : 129</td>
<td align="left">3rd Qu.:69.00</td>
<td align="left">3rd Qu.: 60.00</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">Max. :558</td>
<td align="left">Max. :0.12800</td>
<td align="left">NA</td>
<td align="left">Max. :32.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">OR : 115</td>
<td align="left">Max. :96.00</td>
<td align="left">Max. :138.00</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">(Other):1380</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="plot-missing-data-to-show-it-has-all-been-resolved." class="section level3">
<h3>Plot missing data to show it has all been resolved.</h3>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## 
##  Variables sorted by number of missings: 
##             Variable Count
##                Style     0
##           Brewery_id     0
##                  ABV     0
##           Drink_name     0
##               Ounces     0
##              Brewery     0
##                 City     0
##                State     0
##  median_IBU_by_style     0
##            IBU.clean     0</code></pre>
<pre><code>##     Style             Brewery_id       ABV           Drink_name            Ounces        Brewery              City               State     
##  Length:2348        Min.   :  1   Min.   :0.02700   Length:2348        Min.   : 8.40   Length:2348        Length:2348        CO     : 258  
##  Class :character   1st Qu.: 92   1st Qu.:0.05000   Class :character   1st Qu.:12.00   Class :character   Class :character   CA     : 181  
##  Mode  :character   Median :204   Median :0.05600   Mode  :character   Median :12.00   Mode  :character   Mode  :character   MI     : 146  
##                     Mean   :231   Mean   :0.05967                      Mean   :13.56                                         IN     : 139  
##                     3rd Qu.:366   3rd Qu.:0.06700                      3rd Qu.:16.00                                         TX     : 129  
##                     Max.   :558   Max.   :0.12800                      Max.   :32.00                                         OR     : 115  
##                                                                                                                              (Other):1380  
##  median_IBU_by_style   IBU.clean     
##  Min.   : 8.00       Min.   :  3.57  
##  1st Qu.:21.00       1st Qu.: 21.00  
##  Median :30.00       Median : 32.00  
##  Mean   :40.03       Mean   : 40.46  
##  3rd Qu.:69.00       3rd Qu.: 60.00  
##  Max.   :96.00       Max.   :138.00  
## </code></pre>
</div>
</div>
</div>
<div id="median-abv-and-ibu-per-state-see-output-for-values" class="section level1">
<h1>4. Median ABV and IBU per state (See output for values)</h1>
<p>We can see that there is a difference between states for median IBU and ABV. This is likely due to a variety of reasons such as local laws, climate, demographics, local diet, income per capita, etc. For example, West Virginia has the highest median IBU and New Hampshire has the lowest median IBU per state. Kentucky has the highest median ABV. Utah has the lowest ABV per state (state law mandates 4.0% for most beers)</p>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-10-1.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<pre><code>## [1] &quot;Total Unique Breweries: &quot;</code></pre>
<pre><code>## [1] 558</code></pre>
</div>
<div id="which-state-has-the-maximum-alcoholic-abv-beer-which-state-has-the-most-bitter-ibu-beer-see-output-for-values" class="section level1">
<h1>5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer? (See output for values)</h1>
<ul>
<li>Colorado has the max ABV at 0.128.</li>
<li>Oregon has the most IBU at 138.</li>
</ul>
<table>
<colgroup>
<col width="13%" />
<col width="6%" />
<col width="3%" />
<col width="29%" />
<col width="4%" />
<col width="14%" />
<col width="6%" />
<col width="3%" />
<col width="11%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Style</th>
<th align="right">Brewery_id</th>
<th align="right">ABV</th>
<th align="left">Drink_name</th>
<th align="right">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
<th align="right">median_IBU_by_style</th>
<th align="right">IBU.clean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Quadrupel (Quad)</td>
<td align="right">52</td>
<td align="right">0.128</td>
<td align="left">Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale</td>
<td align="right">19.2</td>
<td align="left">Upslope Brewing Company</td>
<td align="left">Boulder</td>
<td align="left">CO</td>
<td align="right">24</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="left">English Barleywine</td>
<td align="right">2</td>
<td align="right">0.125</td>
<td align="left">London Balling</td>
<td align="right">16.0</td>
<td align="left">Against the Grain Brewery</td>
<td align="left">Louisville</td>
<td align="left">KY</td>
<td align="right">60</td>
<td align="right">80</td>
</tr>
<tr class="odd">
<td align="left">Russian Imperial Stout</td>
<td align="right">18</td>
<td align="right">0.120</td>
<td align="left">Csar</td>
<td align="right">16.0</td>
<td align="left">Tin Man Brewing Company</td>
<td align="left">Evansville</td>
<td align="left">IN</td>
<td align="right">94</td>
<td align="right">90</td>
</tr>
<tr class="even">
<td align="left">Rye Beer</td>
<td align="right">52</td>
<td align="right">0.104</td>
<td align="left">Lee Hill Series Vol. 4 - Manhattan Style Rye Ale</td>
<td align="right">19.2</td>
<td align="left">Upslope Brewing Company</td>
<td align="left">Boulder</td>
<td align="left">CO</td>
<td align="right">57</td>
<td align="right">57</td>
</tr>
<tr class="odd">
<td align="left">Baltic Porter</td>
<td align="right">47</td>
<td align="right">0.100</td>
<td align="left">4Beans</td>
<td align="right">12.0</td>
<td align="left">Sixpoint Craft Ales</td>
<td align="left">Brooklyn</td>
<td align="left">NY</td>
<td align="right">52</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="left">American Barleywine</td>
<td align="right">310</td>
<td align="right">0.099</td>
<td align="left">Old Devil's Tooth</td>
<td align="right">12.0</td>
<td align="left">Sockeye Brewing Company</td>
<td align="left">Boise</td>
<td align="left">ID</td>
<td align="right">96</td>
<td align="right">100</td>
</tr>
</tbody>
</table>
<pre><code>## [1] &quot;Highest ABV State&quot;</code></pre>
<pre><code>##              Style Brewery_id   ABV                                           Drink_name Ounces                 Brewery    City State
## 1 Quadrupel (Quad)         52 0.128 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale   19.2 Upslope Brewing Company Boulder    CO
##   median_IBU_by_style IBU.clean
## 1                  24        24</code></pre>
<table>
<colgroup>
<col width="17%" />
<col width="6%" />
<col width="3%" />
<col width="17%" />
<col width="4%" />
<col width="19%" />
<col width="9%" />
<col width="3%" />
<col width="11%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Style</th>
<th align="right">Brewery_id</th>
<th align="right">ABV</th>
<th align="left">Drink_name</th>
<th align="right">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
<th align="right">median_IBU_by_style</th>
<th align="right">IBU.clean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">American Double / Imperial IPA</td>
<td align="right">375</td>
<td align="right">0.082</td>
<td align="left">Bitter Bitch Imperial IPA</td>
<td align="right">12</td>
<td align="left">Astoria Brewing Company</td>
<td align="left">Astoria</td>
<td align="left">OR</td>
<td align="right">90.5</td>
<td align="right">138</td>
</tr>
<tr class="even">
<td align="left">American IPA</td>
<td align="right">345</td>
<td align="right">0.059</td>
<td align="left">Troopers Alley IPA</td>
<td align="right">12</td>
<td align="left">Wolf Hills Brewing Company</td>
<td align="left">Abingdon</td>
<td align="left">VA</td>
<td align="right">69.0</td>
<td align="right">135</td>
</tr>
<tr class="odd">
<td align="left">American Double / Imperial IPA</td>
<td align="right">231</td>
<td align="right">0.090</td>
<td align="left">Dead-Eye DIPA</td>
<td align="right">16</td>
<td align="left">Cape Ann Brewing Company</td>
<td align="left">Gloucester</td>
<td align="left">MA</td>
<td align="right">90.5</td>
<td align="right">130</td>
</tr>
<tr class="even">
<td align="left">American Double / Imperial IPA</td>
<td align="right">100</td>
<td align="right">0.089</td>
<td align="left">Bay of Bengal Double IPA (2014)</td>
<td align="right">12</td>
<td align="left">Christian Moerlein Brewing Company</td>
<td align="left">Cincinnati</td>
<td align="left">OH</td>
<td align="right">90.5</td>
<td align="right">126</td>
</tr>
<tr class="odd">
<td align="left">American Double / Imperial IPA</td>
<td align="right">273</td>
<td align="right">0.080</td>
<td align="left">Heady Topper</td>
<td align="right">16</td>
<td align="left">The Alchemist</td>
<td align="left">Waterbury</td>
<td align="left">VT</td>
<td align="right">90.5</td>
<td align="right">120</td>
</tr>
<tr class="even">
<td align="left">American Double / Imperial IPA</td>
<td align="right">62</td>
<td align="right">0.097</td>
<td align="left">Abrasive Ale</td>
<td align="right">16</td>
<td align="left">Surly Brewing Company</td>
<td align="left">Brooklyn Center</td>
<td align="left">MN</td>
<td align="right">90.5</td>
<td align="right">120</td>
</tr>
</tbody>
</table>
<pre><code>## [1] &quot;Highest IBU State&quot;</code></pre>
<pre><code>##                            Style Brewery_id   ABV                Drink_name Ounces                 Brewery    City State median_IBU_by_style
## 1 American Double / Imperial IPA        375 0.082 Bitter Bitch Imperial IPA     12 Astoria Brewing Company Astoria    OR                90.5
##   IBU.clean
## 1       138</code></pre>
</div>
<div id="summary-statistics-and-histogram-for-abv-and-ibu" class="section level1">
<h1>6. Summary statistics and Histogram for ABV and IBU</h1>
<p>As can be seen IBU is right skewed. The distribution per state seems fairly similar. Most of the beer is located around the lower IBU which could indicate that more bitter beer is less popular and thus sold less. Similarly the distribution of ABV is right skewed as we would expect for values that can only be positive. It seems that most popular beers will have around 5% ABV so that is the peak we see in the middle. Minimum ABV is 0.027, the maximum ABV is 0.128. The minimum being 2.7 suggests no non-alcoholic beer is present in our dataset and that the lowest ABV is similar to a Raddler or a VERY weak session ale. The highest ABV is consistent with Barley wines, Imperial Stouts, or other High gravity beers. The inter-quartile range for the mean 50% of beers ranges from .050 to .0670 suggesting most craft beers have a fairly predictable ABV.</p>
<table style="width:100%;">
<colgroup>
<col width="2%" />
<col width="10%" />
<col width="8%" />
<col width="9%" />
<col width="10%" />
<col width="8%" />
<col width="10%" />
<col width="10%" />
<col width="8%" />
<col width="12%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Style</th>
<th align="left">Brewery_id</th>
<th align="left">ABV</th>
<th align="left">Drink_name</th>
<th align="left">Ounces</th>
<th align="left">Brewery</th>
<th align="left">City</th>
<th align="left">State</th>
<th align="left">median_IBU_by_style</th>
<th align="left">IBU.clean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Length:2348</td>
<td align="left">Min. : 1</td>
<td align="left">Min. :0.02700</td>
<td align="left">Length:2348</td>
<td align="left">Min. : 8.40</td>
<td align="left">Length:2348</td>
<td align="left">Length:2348</td>
<td align="left">CO : 258</td>
<td align="left">Min. : 8.00</td>
<td align="left">Min. : 3.57</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Class :character</td>
<td align="left">1st Qu.: 92</td>
<td align="left">1st Qu.:0.05000</td>
<td align="left">Class :character</td>
<td align="left">1st Qu.:12.00</td>
<td align="left">Class :character</td>
<td align="left">Class :character</td>
<td align="left">CA : 181</td>
<td align="left">1st Qu.:21.00</td>
<td align="left">1st Qu.: 21.00</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Mode :character</td>
<td align="left">Median :204</td>
<td align="left">Median :0.05600</td>
<td align="left">Mode :character</td>
<td align="left">Median :12.00</td>
<td align="left">Mode :character</td>
<td align="left">Mode :character</td>
<td align="left">MI : 146</td>
<td align="left">Median :30.00</td>
<td align="left">Median : 32.00</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">Mean :231</td>
<td align="left">Mean :0.05967</td>
<td align="left">NA</td>
<td align="left">Mean :13.56</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">IN : 139</td>
<td align="left">Mean :40.03</td>
<td align="left">Mean : 40.46</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">3rd Qu.:366</td>
<td align="left">3rd Qu.:0.06700</td>
<td align="left">NA</td>
<td align="left">3rd Qu.:16.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">TX : 129</td>
<td align="left">3rd Qu.:69.00</td>
<td align="left">3rd Qu.: 60.00</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">Max. :558</td>
<td align="left">Max. :0.12800</td>
<td align="left">NA</td>
<td align="left">Max. :32.00</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">OR : 115</td>
<td align="left">Max. :96.00</td>
<td align="left">Max. :138.00</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">(Other):1380</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
</div>
<div id="relationship-between-the-bitterness-of-the-beer-and-its-alcoholic-content" class="section level1">
<h1>7. Relationship between the bitterness of the beer and its alcoholic content</h1>
<div id="as-can-be-seen-here-are-the-scatter-plots-for-ibu-vs-abv-colorized-by-state-with-a-ordinary-least-squares-regression-line." class="section level3">
<h3>As can be seen, here are the scatter plots for IBU vs ABV, colorized by state with a ordinary least squares regression line.</h3>
<p>These plots suggest visually that there is indeed a linear relationship between IBU and ABV and that there are some outliers at the very high and low ABV values. <img src="BeersAndBrews_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
</div>
<div id="linear-regression" class="section level3">
<h3>Linear Regression</h3>
<p>Note: Assumptions are met for linear regression, we can see that there are many significant interaction terms between ABV and State and that ABV is significant with respect to IBU. Our model includes main effects of State and ABV as well as interactions for State with ABV. For many states, the interaction terms and main effects were found to be significant. For example, the interaction term between the state Migichigan and ABV was found to have a p-value of 0.000211. Significant main effects on IBU from state were also noticed across many states (example ABV P=8.38e-06). In conclusion <img src="BeersAndBrews_files/figure-html/unnamed-chunk-14-1.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-14-2.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-14-3.png" width="672" /></p>
<pre><code>## Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced

## Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-14-4.png" width="672" /></p>
<pre><code>##                     2.5 %        97.5 %
## (Intercept) -2.029943e+02 -5.557743e+01
## StateAL     -3.171919e+01  1.610959e+02
## StateAR      1.873105e+01  3.022028e+02
## StateAZ      4.223290e+01  1.995165e+02
## StateCA      2.426679e+01  1.735989e+02
## StateCO      3.969322e+01  1.885393e+02
## StateCT      2.709379e+01  1.850218e+02
## StateDC     -3.592496e+01  1.596376e+02
## StateDE     -4.996493e+00  4.555682e+02
## StateFL     -8.545280e+00  1.503379e+02
## StateGA     -1.517081e+01  1.858964e+02
## StateHI      9.646861e+00  1.784723e+02
## StateIA      3.499440e+01  1.973795e+02
## StateID      1.044196e+01  1.676403e+02
## StateIL      1.045292e+01  1.619778e+02
## StateIN      4.723884e+01  1.971809e+02
## StateKS      1.470119e+01  1.787877e+02
## StateKY      4.877115e+01  2.065952e+02
## StateLA      3.073658e+00  1.705897e+02
## StateMA      1.170816e+01  1.650841e+02
## StateMD      3.120150e+01  2.018471e+02
## StateME      1.643328e+01  1.741833e+02
## StateMI      6.025551e+01  2.102381e+02
## StateMN      2.235158e+01  1.760193e+02
## StateMO     -5.508943e+00  1.565254e+02
## StateMS     -5.005935e+00  1.768878e+02
## StateMT      2.745614e-02  1.707954e+02
## StateNC      4.231389e+01  1.961367e+02
## StateND     -9.828384e+01  1.894470e+02
## StateNE      2.539617e+01  1.882393e+02
## StateNH      8.715583e+00  2.110638e+02
## StateNJ      1.506322e+01  1.810460e+02
## StateNM     -6.668006e+01  1.304972e+02
## StateNV      4.021690e+01  2.140915e+02
## StateNY      2.442976e+01  1.761810e+02
## StateOH      2.997580e+01  1.861851e+02
## StateOK      1.152842e+01  1.794636e+02
## StateOR      5.000986e+00  1.560456e+02
## StatePA      6.221629e+01  2.136222e+02
## StateRI      3.662376e+01  1.986142e+02
## StateSC      1.389958e+01  1.786749e+02
## StateSD      9.196488e+00  2.708410e+02
## StateTN     -8.927856e+01  2.256904e+02
## StateTX      9.759844e+00  1.602073e+02
## StateUT      5.117993e+01  2.063815e+02
## StateVA      1.352737e+00  1.622822e+02
## StateVT      2.353106e+00  1.616770e+02
## StateWA      4.380150e+01  1.994758e+02
## StateWI      2.488623e+01  1.802204e+02
## StateWV     -3.122755e+02  3.510472e+02
## StateWY     -3.231905e+01  1.599556e+02
## ABV          1.683411e+03  4.319674e+03
## StateAL:ABV -2.828290e+03  4.622201e+02
## StateAR:ABV -5.642426e+03 -3.291640e+02
## StateAZ:ABV -3.694724e+03 -9.113125e+02
## StateCA:ABV -3.117509e+03 -4.543538e+02
## StateCO:ABV -3.404959e+03 -7.494499e+02
## StateCT:ABV -3.343957e+03 -5.588777e+02
## StateDC:ABV -2.957355e+03  3.025984e+02
## StateDE:ABV -7.509553e+03 -9.353292e+01
## StateFL:ABV -2.742573e+03  6.806532e+01
## StateGA:ABV -3.315434e+03  2.519687e+02
## StateHI:ABV -3.293903e+03 -2.906260e+02
## StateIA:ABV -3.662407e+03 -7.972994e+02
## StateID:ABV -2.940741e+03 -1.641119e+02
## StateIL:ABV -2.946349e+03 -2.530816e+02
## StateIN:ABV -3.558914e+03 -8.890956e+02
## StateKS:ABV -3.250293e+03 -3.303854e+02
## StateKY:ABV -3.739902e+03 -9.751429e+02
## StateLA:ABV -3.088269e+03 -1.031970e+02
## StateMA:ABV -2.978856e+03 -2.400355e+02
## StateMD:ABV -3.607993e+03 -6.088146e+02
## StateME:ABV -3.103455e+03 -3.046362e+02
## StateMI:ABV -3.863372e+03 -1.192372e+03
## StateMN:ABV -3.029844e+03 -3.025354e+02
## StateMO:ABV -2.811211e+03  9.048378e+01
## StateMS:ABV -3.064616e+03  1.102774e+02
## StateMT:ABV -3.090981e+03 -4.971947e+01
## StateNC:ABV -3.559235e+03 -8.244883e+02
## StateND:ABV -3.315619e+03  1.906518e+03
## StateNE:ABV -3.409103e+03 -5.251026e+02
## StateNH:ABV -3.875002e+03 -1.726223e+02
## StateNJ:ABV -3.107711e+03 -1.901473e+02
## StateNM:ABV -2.237922e+03  1.146503e+03
## StateNV:ABV -3.781304e+03 -8.292089e+02
## StateNY:ABV -3.131588e+03 -4.259876e+02
## StateOH:ABV -3.336667e+03 -5.801752e+02
## StateOK:ABV -3.327548e+03 -3.781808e+02
## StateOR:ABV -2.668915e+03  2.787855e+01
## StatePA:ABV -3.831445e+03 -1.136083e+03
## StateRI:ABV -3.684933e+03 -8.084058e+02
## StateSC:ABV -3.272199e+03 -3.885799e+02
## StateSD:ABV -4.912777e+03 -4.379245e+02
## StateTN:ABV -4.008628e+03  1.657986e+03
## StateTX:ABV -2.939022e+03 -2.571151e+02
## StateUT:ABV -3.625949e+03 -8.424689e+02
## StateVA:ABV -2.815656e+03  4.590502e+01
## StateVT:ABV -2.803556e+03  4.054335e-02
## StateWA:ABV -3.500037e+03 -7.273079e+02
## StateWI:ABV -3.394402e+03 -6.088908e+02
## StateWV:ABV -5.664767e+03  5.061681e+03
## StateWY:ABV -2.961487e+03  4.869884e+02</code></pre>
<pre><code>## 
## Call:
## lm(formula = IBU.clean ~ State + State * ABV + ABV, data = bdat.imputed.IBU.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -79.146 -12.212  -1.991  12.028  87.085 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -129.29      37.59  -3.440 0.000593 ***
## StateAL        64.69      49.16   1.316 0.188368    
## StateAR       160.47      72.28   2.220 0.026506 *  
## StateAZ       120.87      40.10   3.014 0.002606 ** 
## StateCA        98.93      38.08   2.598 0.009428 ** 
## StateCO       114.12      37.95   3.007 0.002668 ** 
## StateCT       106.06      40.27   2.634 0.008500 ** 
## StateDC        61.86      49.86   1.241 0.214906    
## StateDE       225.29     117.43   1.918 0.055178 .  
## StateFL        70.90      40.51   1.750 0.080241 .  
## StateGA        85.36      51.27   1.665 0.096033 .  
## StateHI        94.06      43.05   2.185 0.028982 *  
## StateIA       116.19      41.40   2.806 0.005056 ** 
## StateID        89.04      40.08   2.222 0.026413 *  
## StateIL        86.22      38.63   2.232 0.025741 *  
## StateIN       122.21      38.23   3.197 0.001410 ** 
## StateKS        96.74      41.84   2.312 0.020845 *  
## StateKY       127.68      40.24   3.173 0.001529 ** 
## StateLA        86.83      42.71   2.033 0.042172 *  
## StateMA        88.40      39.11   2.260 0.023891 *  
## StateMD       116.52      43.51   2.678 0.007457 ** 
## StateME        95.31      40.22   2.370 0.017892 *  
## StateMI       135.25      38.24   3.537 0.000413 ***
## StateMN        99.19      39.18   2.531 0.011425 *  
## StateMO        75.51      41.31   1.828 0.067731 .  
## StateMS        85.94      46.38   1.853 0.064002 .  
## StateMT        85.41      43.54   1.962 0.049926 *  
## StateNC       119.23      39.22   3.040 0.002394 ** 
## StateND        45.58      73.36   0.621 0.534452    
## StateNE       106.82      41.52   2.573 0.010155 *  
## StateNH       109.89      51.59   2.130 0.033284 *  
## StateNJ        98.05      42.32   2.317 0.020596 *  
## StateNM        31.91      50.27   0.635 0.525694    
## StateNV       127.15      44.33   2.868 0.004167 ** 
## StateNY       100.31      38.69   2.592 0.009592 ** 
## StateOH       108.08      39.83   2.714 0.006706 ** 
## StateOK        95.50      42.82   2.230 0.025829 *  
## StateOR        80.52      38.51   2.091 0.036651 *  
## StatePA       137.92      38.60   3.573 0.000361 ***
## StateRI       117.62      41.30   2.848 0.004443 ** 
## StateSC        96.29      42.01   2.292 0.022006 *  
## StateSD       140.02      66.71   2.099 0.035939 *  
## StateTN        68.21      80.31   0.849 0.395799    
## StateTX        84.98      38.36   2.215 0.026829 *  
## StateUT       128.78      39.57   3.254 0.001153 ** 
## StateVA        81.82      41.03   1.994 0.046274 *  
## StateVT        82.02      40.62   2.019 0.043611 *  
## StateWA       121.64      39.69   3.065 0.002206 ** 
## StateWI       102.55      39.61   2.589 0.009677 ** 
## StateWV        19.39     169.13   0.115 0.908754    
## StateWY        63.82      49.02   1.302 0.193128    
## ABV          3001.54     672.17   4.465 8.38e-06 ***
## StateAL:ABV -1183.04     838.98  -1.410 0.158652    
## StateAR:ABV -2985.79    1354.72  -2.204 0.027626 *  
## StateAZ:ABV -2303.02     709.68  -3.245 0.001191 ** 
## StateCA:ABV -1785.93     679.02  -2.630 0.008593 ** 
## StateCO:ABV -2077.20     677.07  -3.068 0.002181 ** 
## StateCT:ABV -1951.42     710.11  -2.748 0.006043 ** 
## StateDC:ABV -1327.38     831.19  -1.597 0.110414    
## StateDE:ABV -3801.54    1890.86  -2.010 0.044499 *  
## StateFL:ABV -1337.25     716.63  -1.866 0.062166 .  
## StateGA:ABV -1531.73     909.58  -1.684 0.092320 .  
## StateHI:ABV -1792.26     765.74  -2.341 0.019342 *  
## StateIA:ABV -2229.85     730.51  -3.052 0.002296 ** 
## StateID:ABV -1552.43     707.95  -2.193 0.028422 *  
## StateIL:ABV -1599.72     686.70  -2.330 0.019917 *  
## StateIN:ABV -2224.00     680.72  -3.267 0.001103 ** 
## StateKS:ABV -1790.34     744.49  -2.405 0.016262 *  
## StateKY:ABV -2357.52     704.93  -3.344 0.000838 ***
## StateLA:ABV -1595.73     761.10  -2.097 0.036140 *  
## StateMA:ABV -1609.45     698.31  -2.305 0.021271 *  
## StateMD:ABV -2108.40     764.70  -2.757 0.005878 ** 
## StateME:ABV -1704.05     713.61  -2.388 0.017027 *  
## StateMI:ABV -2527.87     681.02  -3.712 0.000211 ***
## StateMN:ABV -1666.19     695.38  -2.396 0.016653 *  
## StateMO:ABV -1360.36     739.84  -1.839 0.066088 .  
## StateMS:ABV -1477.17     809.50  -1.825 0.068165 .  
## StateMT:ABV -1570.35     775.43  -2.025 0.042971 *  
## StateNC:ABV -2191.86     697.28  -3.143 0.001691 ** 
## StateND:ABV  -704.55    1331.48  -0.529 0.596756    
## StateNE:ABV -1967.10     735.33  -2.675 0.007524 ** 
## StateNH:ABV -2023.81     943.99  -2.144 0.032149 *  
## StateNJ:ABV -1648.93     743.89  -2.217 0.026748 *  
## StateNM:ABV  -545.71     862.92  -0.632 0.527193    
## StateNV:ABV -2305.26     752.69  -3.063 0.002220 ** 
## StateNY:ABV -1778.79     689.84  -2.579 0.009985 ** 
## StateOH:ABV -1958.42     702.82  -2.787 0.005373 ** 
## StateOK:ABV -1852.86     752.00  -2.464 0.013817 *  
## StateOR:ABV -1320.52     687.60  -1.920 0.054924 .  
## StatePA:ABV -2483.76     687.23  -3.614 0.000308 ***
## StateRI:ABV -2246.67     733.43  -3.063 0.002215 ** 
## StateSC:ABV -1830.39     735.23  -2.490 0.012863 *  
## StateSD:ABV -2675.35    1140.95  -2.345 0.019122 *  
## StateTN:ABV -1175.32    1444.81  -0.813 0.416031    
## StateTX:ABV -1598.07     683.80  -2.337 0.019525 *  
## StateUT:ABV -2234.21     709.70  -3.148 0.001665 ** 
## StateVA:ABV -1384.88     729.61  -1.898 0.057811 .  
## StateVT:ABV -1401.76     714.83  -1.961 0.050007 .  
## StateWA:ABV -2113.67     706.96  -2.990 0.002822 ** 
## StateWI:ABV -2001.65     710.22  -2.818 0.004869 ** 
## StateWV:ABV  -301.54    2734.91  -0.110 0.912216    
## StateWY:ABV -1237.25     879.26  -1.407 0.159519    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.75 on 2246 degrees of freedom
## Multiple R-squared:  0.4258, Adjusted R-squared:    0.4 
## F-statistic: 16.49 on 101 and 2246 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="difference-with-respect-to-ibu-and-abv-between-ipas-and-other-ales" class="section level1">
<h1>8. Difference with respect to IBU and ABV between IPAs and other Ales</h1>
<p>To investigate the difference between <code>IBU</code> and <code>ABV</code> for <code>IPA's vs OtherAles</code> we first perform some nominal data cleanup and visualize IBU vs ABV for <code>IPA's vs otherAles</code>. We then use KNN to classify style, either <code>IPA</code> or <code>otherAle</code>, to highlight that there is a significant difference between the relationship of IBU and ABV for <code>IPA's</code> and <code>otherAles</code></p>
<div id="data-prep-and-visualization" class="section level3">
<h3>Data Prep and Visualization</h3>
<ol style="list-style-type: decimal">
<li>Filter out all data that is not an <code>Ale</code>. Then bucket anything with <code>IPA</code> or <code>India Pale Ale</code> as <code>IPA</code> and all other beers with the word <code>Ale</code> in their style as <code>OtherAle</code>.<br />
</li>
<li>Plot distributions for ABV for <code>IPA's</code> and <code>otherAles</code></li>
<li>Then plot IBU and ABV for <code>IPA's</code> and <code>otherAles</code> for IPA's and OtherALes</li>
</ol>
<p><strong>Note: American Pale Ale is VERY similar to IPA but we call it &quot;other&quot; ale</strong></p>
<pre><code>##                    Abbey Single Ale                             Altbier              American Adjunct Lager            American Amber / Red Ale 
##                                   2                                  13                                  18                                 132 
##          American Amber / Red Lager                 American Barleywine                  American Black Ale                 American Blonde Ale 
##                                  28                                   3                                  36                                 108 
##                  American Brown Ale             American Dark Wheat Ale      American Double / Imperial IPA  American Double / Imperial Pilsner 
##                                  70                                   7                                 105                                   2 
##    American Double / Imperial Stout           American India Pale Lager                        American IPA             American Pale Ale (APA) 
##                                   9                                   3                                 423                                 244 
##                 American Pale Lager             American Pale Wheat Ale                    American Pilsner                     American Porter 
##                                  38                                  96                                  25                                  67 
##                      American Stout                 American Strong Ale                  American White IPA                   American Wild Ale 
##                                  39                                  14                                  11                                   6 
##                       Baltic Porter                    Belgian Dark Ale                         Belgian IPA                    Belgian Pale Ale 
##                                   6                                  11                                  18                                  24 
##             Belgian Strong Dark Ale             Belgian Strong Pale Ale                  Berliner Weissbier                      Bière de Garde 
##                                   6                                   7                                  11                                   7 
##                                Bock      California Common / Steam Beer                          Chile Beer                           Cream Ale 
##                                   7                                   6                                   3                                  29 
##                      Czech Pilsener                          Doppelbock           Dortmunder / Export Lager                              Dubbel 
##                                  28                                   7                                   6                                   5 
##                        Dunkelweizen                  English Barleywine                      English Bitter                   English Brown Ale 
##                                   4                                   3                                   3                                  18 
##               English Dark Mild Ale        English India Pale Ale (IPA)                    English Pale Ale               English Pale Mild Ale 
##                                   6                                  13                                  12                                   3 
##                       English Stout                  English Strong Ale                     Euro Dark Lager                     Euro Pale Lager 
##                                   2                                   4                                   5                                   2 
## Extra Special / Strong Bitter (ESB)                  Flanders Oud Bruin              Foreign / Export Stout              Fruit / Vegetable Beer 
##                                  20                                   1                                   6                                  49 
##                     German Pilsener                                Gose                            Grisette                          Hefeweizen 
##                                  36                                  10                                   1                                  40 
##                Herbed / Spiced Beer                     Irish Dry Stout                       Irish Red Ale          Keller Bier / Zwickel Bier 
##                                   9                                   5                                  12                                   3 
##                              Kölsch                               Lager                         Light Lager               Maibock / Helles Bock 
##                                  42                                   1                                  12                                   5 
##                Märzen / Oktoberfest                  Milk / Sweet Stout                 Munich Dunkel Lager                 Munich Helles Lager 
##                                  30                                  10                                   4                                  20 
##                       Oatmeal Stout                             Old Ale                               Other                         Pumpkin Ale 
##                                  18                                   2                                   1                                  23 
##                    Quadrupel (Quad)                              Radler                          Roggenbier              Russian Imperial Stout 
##                                   4                                   3                                   2                                  11 
##                            Rye Beer              Saison / Farmhouse Ale                         Schwarzbier              Scotch Ale / Wee Heavy 
##                                  18                                  52                                   9                                  15 
##            Scottish-Style Amber Ale                        Scottish Ale                         Smoked Beer                              Tripel 
##                                   1                                  19                                   1                                  11 
##                        Vienna Lager                           Wheat Ale                       Winter Warmer                             Witbier 
##                                  20                                   1                                  15                                  51</code></pre>
<pre><code>##      Style Brewery_id   ABV                   Drink_name Ounces                         Brewery          City State median_IBU_by_style IBU.clean
## 1 OtherAle         58 0.049      Abbey&#39;s Single (2015- )     12                 Destihl Brewery   Bloomington    IL                  22        22
## 2 OtherAle         58 0.049 Abbey&#39;s Single Ale (Current)     12                 Destihl Brewery   Bloomington    IL                  22        22
## 3 OtherAle        361 0.061                  Hot Rod Red     12         Aviator Brewing Company Fuquay-Varina    NC                  30        41
## 4 OtherAle        553 0.056      Mickey Finn&#39;s Amber Ale     12           Mickey Finn&#39;s Brewery  Libertyville    IL                  30        30
## 5 OtherAle        102 0.052          Hurricane Amber Ale     12 Coastal Extreme Brewing Company       Newport    RI                  30        24
## 6 OtherAle         83 0.052    Fat Tire Amber Ale (2011)     12     New Belgium Brewing Company  Fort Collins    CO                  30        18</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="BeersAndBrews_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<pre><code>##    Length     Class      Mode 
##      2348 character character</code></pre>
</div>
<div id="test-split" class="section level3">
<h3>Test split</h3>
<p>Split the data into 85% train and 15% test. Only train our algorithms on training data with crossvalidation. Use test split only for accuracy and prediction metric calculation.</p>
</div>
<div id="knn-for-ipas-vs-other-ales" class="section level3">
<h3>KNN for <code>IPA's</code> vs <code>Other Ales</code></h3>
<pre><code>## Confusion Matrix and Statistics
## 
##           classifications
##            IPA OtherAle
##   IPA       66        8
##   OtherAle  16      140
##                                          
##                Accuracy : 0.8957         
##                  95% CI : (0.8487, 0.932)
##     No Information Rate : 0.6435         
##     P-Value [Acc &gt; NIR] : &lt;2e-16         
##                                          
##                   Kappa : 0.7675         
##                                          
##  Mcnemar&#39;s Test P-Value : 0.153          
##                                          
##             Sensitivity : 0.8049         
##             Specificity : 0.9459         
##          Pos Pred Value : 0.8919         
##          Neg Pred Value : 0.8974         
##              Prevalence : 0.3565         
##          Detection Rate : 0.2870         
##    Detection Prevalence : 0.3217         
##       Balanced Accuracy : 0.8754         
##                                          
##        &#39;Positive&#39; Class : IPA            
## </code></pre>
</div>
<div id="ols-multiple-linear-regression-for-ipas-vs-other-ales" class="section level3">
<h3>OLS Multiple Linear Regression for <code>IPA's</code> vs <code>Other Ales</code></h3>
<p>Use least squared multiple linear regression to highlight specific relationships between IBU and ABV for style IPA and style otherAle. - NOTE: make the unit increase in interpretation be in terms of .01 unit increase in ABV <img src="BeersAndBrews_files/figure-html/unnamed-chunk-18-1.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-18-2.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-18-3.png" width="672" /><img src="BeersAndBrews_files/figure-html/unnamed-chunk-18-4.png" width="672" /></p>
<pre><code>##                        2.5 %     97.5 %
## (Intercept)          8.43918  22.634170
## StyleOtherAle      -23.62164  -6.044308
## ABV                707.65116 912.224759
## StyleOtherAle:ABV -371.92932 -99.601412</code></pre>
<pre><code>## 
## Call:
## lm(formula = IBU.clean ~ Style + Style * ABV + ABV, data = bdat.IPA.Vs.Ales.train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.902  -9.135  -2.283   8.278  76.975 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         15.537      3.618   4.294 1.88e-05 ***
## StyleOtherAle      -14.833      4.480  -3.311 0.000955 ***
## ABV                809.938     52.139  15.534  &lt; 2e-16 ***
## StyleOtherAle:ABV -235.765     69.408  -3.397 0.000702 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.42 on 1296 degrees of freedom
## Multiple R-squared:  0.6575, Adjusted R-squared:  0.6567 
## F-statistic: 829.3 on 3 and 1296 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="lda-and-knn-to-predict-style-based-on-ibu-and-abv-individually" class="section level3">
<h3>LDA and KNN to predict style based on IBU and ABV Individually</h3>
<p>Here we use LDA and KNN to assess the relationship between IBU and Style as well as ABV and style.</p>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion:</h3>
<p>It is clear that there is a significant relationship between IBU and ABV and that the relationship varies for <code>IPA's</code> and for <code>other Ales</code>. We were able to predict the style of Ale (either IPA or other Ales) with an average Accuracy of 90% (P-value &lt; 2e-16). Further, we can be 95% confident that the true accuracy for our model is between [0.8537, 0.9355]. On average, holding all other variables constant, we predict that when an ale is an IPA, it has a 2.373 increase in IBU per .01 increase in relative ABV, when compared to Other Ales. That is to say, IPA's generally have a higher bitterness for a given ABV than other ales and the ratio of IBU to ABV is generally higher for IPA's. We are 95% confident that this 'IPA' effect is between [1.01203617 3.73372852] per .01 increase in ABV. This 'IPA' effect applies to all craft beers sampled in the study, as well as all craft beers in the USA for which the beers sampled int the study are a good representation. Reasons for this 'IPA' effect could be simply that IPA's, on average, use a higher ratio of hops in the brewing process and will generally have higher bitterness for the same ABV when compared to other Ales.</p>
<p>That said, it can be noted that IPA's generally have a higher ABV (IBU not fixed). The skew of IPA's toward higher ABV could also be due to the fact beer drinkers generally drink fewer IPA's and are willing to spend more money on them. As such, to achieve the same 'buzz' the discerning IPA drinker will gravitate towards higher IBU AND Higher ABV.</p>
</div>
</div>
<div id="we-will-knock-your-socks-off" class="section level1">
<h1>9. We will knock your socks off!</h1>
<p>To show that there is a relationship between State and Ounces for all Ales, specifically 12 vs 16 ounces, we perform a brief analysis of Ounces vs. State. What we are interested in here is whether or not a State like California or Michigan differ in their preference for 12 vs 16 ounce beers.</p>
<div id="data-cleanup-and-visualization" class="section level3">
<h3>Data Cleanup and Visualization</h3>
<ol style="list-style-type: decimal">
<li>Filter out all ales that are not either <code>12</code> or <code>16</code> ounces in volume.</li>
<li>We plot the ratios of <code>12</code> vs <code>16</code> ounce Ales for each state.<br />
<img src="BeersAndBrews_files/figure-html/unnamed-chunk-20-1.png" width="672" /></li>
</ol>
</div>
<div id="analysis-knn-confusion-matrix" class="section level3">
<h3>Analysis: KNN &amp; confusion matrix</h3>
<ol style="list-style-type: decimal">
<li>We use KNN with the optimal cross validated value of K (usually k=8) to predict Ounces (12 or 16) by state.</li>
<li>Generate a confusion matrix via test data to assess the performance of the prediction</li>
<li>Accuracy ends up being around 0.7137 which is roughly 21% better than the existing random chance that we would have for predicting either 12 or 16 ounces.</li>
</ol>
<pre><code>## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV

## Warning in preProcess.default(thresh = 0.95, k = 5, freqCut = 19, uniqueCut = 10, : These variables have zero variances: StateAR, StateWV</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##     classifications
##       12  16
##   12 127  13
##   16  51  36
##                                           
##                Accuracy : 0.7181          
##                  95% CI : (0.6547, 0.7756)
##     No Information Rate : 0.7841          
##     P-Value [Acc &gt; NIR] : 0.9925          
##                                           
##                   Kappa : 0.3499          
##                                           
##  Mcnemar&#39;s Test P-Value : 3.746e-06       
##                                           
##             Sensitivity : 0.7135          
##             Specificity : 0.7347          
##          Pos Pred Value : 0.9071          
##          Neg Pred Value : 0.4138          
##              Prevalence : 0.7841          
##          Detection Rate : 0.5595          
##    Detection Prevalence : 0.6167          
##       Balanced Accuracy : 0.7241          
##                                           
##        &#39;Positive&#39; Class : 12              
## </code></pre>
</div>
<div id="conclusion-1" class="section level3">
<h3>Conclusion:</h3>
<p>There is a significant relationship between <code>Ounces</code> and <code>State</code> for Ales that are either 12 vs 16 ounces. We were able to predict ounces by state (for ales) with an accuracy of 71.4% which is significantly better than random chance (50% accuracy). This suggests that when considering what size a beer should be sold in, it could be important to consider what state that beer is going to be brewed in. This helps align sales with the laws and preferences of that state. For example, Indiana has a high prevalence of 16 ounce ales, whereas Colorado or Texas both lean towards 12 ounce ales. It would be preferable to brew and sell 16 ounce beers in states like Indiana (or other states that have more 16 ounce ales) and 12 ounce beers in Colorado (or other states that have more 12 ounce ales). The reason for this association may be due to a variety of reasons including income, weather, local diet, and social norms for beer drinkers.</p>
</div>
</div>
<div id="overall-conclusion" class="section level1">
<h1>Overall Conclusion:</h1>
<p>There are several note-worthy relationships in our craft beer dataset. For example, median IBU as well as median ABV per state vary by state for craft beers. When targeting sales of particular states' craft beer, it would be wise to consider the median IBU and median ABV for the current craft beers in that state.</p>
<p>Further, it is clear that there is a significant relationship between IBU and ABV and that the relationship varies for <code>IPA's</code> and for <code>other Ales</code>. We were able to predict the style of Ale (either IPA or other Ales) with an average Accuracy of 90% (P-value &lt; 2e-16). Further, we can be 95% confident that the true accuracy for our model is between [0.8537, 0.9355]. On average, holding all other variables constant, we predict that when an ale is an IPA, it has a 2.373 increase in IBU per .01 increase in relative ABV, when compared to Other Ales. That is to say, IPA's generally have a higher bitterness for a given ABV than other ales and the ratio of IBU to ABV is generally higher for IPA's. We are 95% confident that this 'IPA' effect is between [1.01203617 3.73372852] per .01 increase in ABV. This 'IPA' effect applies to all craft beers sampled in the study, as well as all craft beers in the USA for which the beers sampled in the study are a good representation. Reasons for this 'IPA' effect could be simply that IPA's, on average, use a higher ratio of hops in the brewing process and will generally have higher bitterness for the same ABV when compared to other Ales.</p>
<p>That said, it can be noted that IPA's generally have a higher ABV (IBU not fixed). The skew of IPA's toward higher ABV could also be due to the fact beer drinkers generally drink fewer IPA's and are willing to spend more money on them. As such, to achieve the same 'buzz' the discerning IPA drinker will gravitate towards higher IBU AND higher ABV.</p>
<p>There is also a significant relationship between <code>Ounces</code> and <code>State</code> for Ales that are either 12 vs 16 ounces. We were able to predict ounces by state (for ales) with an accuracy of 71.4% which is significantly better than random chance (50% accuracy). This suggests that when considering what size a beer should be sold in, it could be important to consider what state that beer is going to be brewed in. This helps align sales with the laws and preferences of that state. For example, Indiana has a high prevalence of 16 ounce ales, whereas Colorado or Texas both lean towards 12 ounce ales. It would be preferable to brew and sell 16 ounce beers in states like Indiana (or other states that have more 16 ounce ales) and 12 ounce beers in Colorado (or other states that have more 12 ounce ales). The reason for this association may be due to a variety of reasons including income, weather, local diet, and social norms for beer drinkers.</p>
<p>We recommend that Anheuser-Busch InBev stay consistent with established patterns for given states. To tend towards breweries which produce IPA's and Ale's that can be accurately predicted with our models above. To favor beers and breweries who have average ABV, IBU, and volume not dissimilar from established norms for that state. Given how strapped the market for craft beer and craft breweires is, the opportuinty is ripe.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
